/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unisinu.taller.Interface;
import javax.swing.JOptionPane;

/**
 *
 * @author ING-LUIS-_-
 */
public class Resultado extends javax.swing.JFrame {

    /**
     * Creates new form Resultado
     */
    public Resultado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        btnDatos = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        RESULTADOid = new javax.swing.JLabel();
        RESULTADOclave = new javax.swing.JLabel();
        RESULTADOnombre = new javax.swing.JLabel();
        RESULTADOnombrec = new javax.swing.JLabel();
        RESULTADOnivel = new javax.swing.JLabel();
        RESULTADOsintomas = new javax.swing.JLabel();
        RESULTADOmedicamento = new javax.swing.JLabel();
        RESULTADOcontagiosa = new javax.swing.JLabel();
        RESULTADOcubierta = new javax.swing.JLabel();
        RESULTADOincapacidad = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        menuCambiar = new javax.swing.JMenu();
        menuNombre = new javax.swing.JMenuItem();
        menuCientifico = new javax.swing.JMenuItem();
        menuGravedad = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 0, 0));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unisinu/taller/Interface/imagenes/icon.png"))); // NOI18N
        titulo.setText(" DATOS DE ENFERMEDADES");
        titulo.setAlignmentY(2.0F);
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 650, 84));

        btnDatos.setBackground(new java.awt.Color(255, 255, 255));
        btnDatos.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        btnDatos.setText("MOSTRAR DATOS");
        btnDatos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
        btnDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosActionPerformed(evt);
            }
        });
        getContentPane().add(btnDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 180, 40));

        jPanel1.setLayout(new java.awt.GridLayout(5, 2));

        RESULTADOid.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        RESULTADOid.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2), "ID:  ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("DialogInput", 1, 18))); // NOI18N
        jPanel1.add(RESULTADOid);

        RESULTADOclave.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        RESULTADOclave.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2), "CLAVE:  ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("DialogInput", 1, 18))); // NOI18N
        jPanel1.add(RESULTADOclave);

        RESULTADOnombre.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        RESULTADOnombre.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2), "NOMBRE DE LA ENFERMEDAD: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DialogInput", 1, 18))); // NOI18N
        jPanel1.add(RESULTADOnombre);

        RESULTADOnombrec.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        RESULTADOnombrec.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2), "NOMBRE DEL CIENTIFICO: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DialogInput", 1, 18))); // NOI18N
        jPanel1.add(RESULTADOnombrec);

        RESULTADOnivel.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        RESULTADOnivel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2), "NIVEL DE GRAVEDAD: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DialogInput", 1, 18))); // NOI18N
        jPanel1.add(RESULTADOnivel);

        RESULTADOsintomas.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        RESULTADOsintomas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2), "SINTOMAS: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DialogInput", 1, 18))); // NOI18N
        jPanel1.add(RESULTADOsintomas);

        RESULTADOmedicamento.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        RESULTADOmedicamento.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2), "MEDICAMENTOS:  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DialogInput", 1, 18))); // NOI18N
        jPanel1.add(RESULTADOmedicamento);

        RESULTADOcontagiosa.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        RESULTADOcontagiosa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2), "CONTAGIOSA:  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DialogInput", 1, 18))); // NOI18N
        jPanel1.add(RESULTADOcontagiosa);

        RESULTADOcubierta.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        RESULTADOcubierta.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2), "CUBIERTA POR POST:  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DialogInput", 1, 18))); // NOI18N
        jPanel1.add(RESULTADOcubierta);

        RESULTADOincapacidad.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        RESULTADOincapacidad.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2), "REQUIERE INCAPACIDAD:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DialogInput", 1, 18))); // NOI18N
        jPanel1.add(RESULTADOincapacidad);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 84, 910, 440));

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 540, 180, 40));

        menu.setText("Menu");

        menuCambiar.setText("Cambiar");

        menuNombre.setText("Nombre de la enfermedad");
        menuNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNombreActionPerformed(evt);
            }
        });
        menuCambiar.add(menuNombre);

        menuCientifico.setText("Nombre del Cientifico");
        menuCientifico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCientificoActionPerformed(evt);
            }
        });
        menuCambiar.add(menuCientifico);

        menuGravedad.setText("Nivel de Gravedad");
        menuGravedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGravedadActionPerformed(evt);
            }
        });
        menuCambiar.add(menuGravedad);

        jMenuItem1.setText("Sintomas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuCambiar.add(jMenuItem1);

        jMenuItem2.setText("Medicamentos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuCambiar.add(jMenuItem2);

        jMenuItem3.setText("Contagiosa");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuCambiar.add(jMenuItem3);

        jMenuItem4.setText("Cubierta Por Post");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuCambiar.add(jMenuItem4);

        jMenuItem5.setText("Incapacidad");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuCambiar.add(jMenuItem5);

        menu.add(menuCambiar);
        menu.add(jSeparator1);

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Enfermedades abp = new Enfermedades();
    private void btnDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosActionPerformed
        RESULTADOid.setText("" + abp.id);
        RESULTADOclave.setText(abp.clave);
        RESULTADOnombre.setText(abp.nombre);
        RESULTADOnombrec.setText(abp.NombreCientifico);
        RESULTADOsintomas.setText(abp.sintomas);
        RESULTADOmedicamento.setText(abp.medicamentos);
        RESULTADOnivel.setText("" + abp.NivelGravedad);
        RESULTADOincapacidad.setText(abp.requiereIncapacidad);
        RESULTADOcontagiosa.setText(abp.esContagiosa);
        RESULTADOcubierta.setText(abp.esCubiertaporPost);
        btnDatos.setText("ACTUALIZAR");
    }//GEN-LAST:event_btnDatosActionPerformed

    private void menuNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNombreActionPerformed
        abp.nombre = JOptionPane.showInputDialog(null, "Ingrese el nombre de La enfermedad");
    }//GEN-LAST:event_menuNombreActionPerformed

    private void menuCientificoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCientificoActionPerformed
        abp.NombreCientifico = JOptionPane.showInputDialog(null, "Ingrese el nombre del Cientifico");
    }//GEN-LAST:event_menuCientificoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        abp.sintomas = JOptionPane.showInputDialog(null, "Ingrese los Sintomas");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        abp.medicamentos = JOptionPane.showInputDialog(null, "Ingrese los Medicamentos");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        JOptionPane.showMessageDialog(null, "Gracias Por Utilizar nuestra Herramienta :) ");
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "¿Es Contagiosa?");
        if(x == 0){//arroja 0 si es si 
            abp.esContagiosa = "SI";
        }
        else if(x == 1){//ARROJA 1 SI ES NO 
            abp.esContagiosa = "NO";
        }
        else{
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "¿Es Cubirta por Post?");
        if(x == 0){
            abp.esCubiertaporPost = "SI";
        }
        else if(x == 1){
            abp.esCubiertaporPost = "NO";
        }
        else{
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "¿Requiere incapacidad?");
        if(x == 0){
            abp.requiereIncapacidad = "SI";
        }
        else if(x == 1){
            abp.requiereIncapacidad = "NO";
        }
        else{
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void menuGravedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGravedadActionPerformed
        int error;
        do{
            error = 0;
            try{
                abp.NivelGravedad = Integer.parseInt(JOptionPane.showInputDialog(null, "Nivel de Greavedad"));
                if(abp.NivelGravedad > 10 || abp.NivelGravedad < 1){
                    JOptionPane.showMessageDialog(null, "Debe ser numeros entre 1 - 10");
                    error++;
                }
            }
            catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "Debe ser numeros entre 1 - 10");
                error++;
            }
        }while(error > 0);
    }//GEN-LAST:event_menuGravedadActionPerformed
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resultado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RESULTADOclave;
    private javax.swing.JLabel RESULTADOcontagiosa;
    private javax.swing.JLabel RESULTADOcubierta;
    private javax.swing.JLabel RESULTADOid;
    private javax.swing.JLabel RESULTADOincapacidad;
    private javax.swing.JLabel RESULTADOmedicamento;
    private javax.swing.JLabel RESULTADOnivel;
    private javax.swing.JLabel RESULTADOnombre;
    private javax.swing.JLabel RESULTADOnombrec;
    private javax.swing.JLabel RESULTADOsintomas;
    private javax.swing.JButton btnDatos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menu;
    private javax.swing.JMenu menuCambiar;
    private javax.swing.JMenuItem menuCientifico;
    private javax.swing.JMenuItem menuGravedad;
    private javax.swing.JMenuItem menuNombre;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
