/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unisinu.taller.Interface;

import java.awt.Color;

/**
 *
 * @author ING-LUIS-_-
 */
public class Ventana2 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana2() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        txtCientifico = new javax.swing.JTextField();
        slGravedad = new javax.swing.JSlider();
        btnSiguiente = new javax.swing.JButton();
        etiNombreIncorrecto = new javax.swing.JLabel();
        etiCientificoIncorrecto = new javax.swing.JLabel();
        etigravedad0 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(906, 700));
        setMinimumSize(new java.awt.Dimension(906, 700));
        setPreferredSize(new java.awt.Dimension(906, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "NOMBRE DE LA ENFERMEDAD ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("DialogInput", 1, 18), new java.awt.Color(255, 0, 0))); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 370, 80));

        txtCientifico.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        txtCientifico.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "NOMBRE CIENTIFICO ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("DialogInput", 1, 18), new java.awt.Color(255, 0, 0))); // NOI18N
        getContentPane().add(txtCientifico, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 370, 80));

        slGravedad.setBackground(new java.awt.Color(255, 255, 255));
        slGravedad.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        slGravedad.setMajorTickSpacing(1);
        slGravedad.setMaximum(10);
        slGravedad.setPaintLabels(true);
        slGravedad.setPaintTicks(true);
        slGravedad.setToolTipText("");
        slGravedad.setValue(0);
        slGravedad.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "NIVEL DE GRAVEDAD DE LA ENFERMEDAD", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("DialogInput", 1, 18), new java.awt.Color(255, 0, 0))); // NOI18N
        getContentPane().add(slGravedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 548, 77));

        btnSiguiente.setBackground(new java.awt.Color(255, 255, 255));
        btnSiguiente.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        btnSiguiente.setText("SIGUIENTE");
        btnSiguiente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, 200, 40));

        etiNombreIncorrecto.setFont(new java.awt.Font("DialogInput", 2, 12)); // NOI18N
        etiNombreIncorrecto.setForeground(new java.awt.Color(255, 0, 0));
        etiNombreIncorrecto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(etiNombreIncorrecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 251, 20));

        etiCientificoIncorrecto.setFont(new java.awt.Font("DialogInput", 2, 12)); // NOI18N
        etiCientificoIncorrecto.setForeground(new java.awt.Color(255, 0, 0));
        etiCientificoIncorrecto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(etiCientificoIncorrecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 246, 20));

        etigravedad0.setFont(new java.awt.Font("DialogInput", 2, 12)); // NOI18N
        etigravedad0.setForeground(new java.awt.Color(255, 0, 0));
        etigravedad0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(etigravedad0, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 242, 20));

        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 0, 0));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unisinu/taller/Interface/imagenes/icon.png"))); // NOI18N
        titulo.setText("BASE DE DATOS PARA\n ENFERMEDADES");
        titulo.setAlignmentY(2.0F);
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 819, 101));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Enfermedades abp = new Enfermedades();
    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        
        abp.nombre = txtNombre.getText();
        etiNombreIncorrecto.setText("");
	int errores = 0;
        abp.nombre = abp.nombre.trim();
        if(abp.nombre.isEmpty() == true){
            etiNombreIncorrecto.setText("Ingrese el nombre de la Enfermedad");
            errores++;
        }
        
        //*********************
        abp.NombreCientifico = txtCientifico.getText();
        etiCientificoIncorrecto.setText("");
        errores = 0;
       abp.NombreCientifico = abp.NombreCientifico.trim();
       if(abp.NombreCientifico.isEmpty()== true){
           etiCientificoIncorrecto.setText("Ingrese el nombre cientifico de la enfermedad");
           errores++;
       }
       
      
 
        //***********************************************
        abp.NivelGravedad = slGravedad.getValue();
        etigravedad0.setText("");
        if(abp.NivelGravedad == 0){
            etigravedad0.setText("Seleccione un nivel de gravedad");
        }
        
        //**************************************************
        
        if(errores == 0 && abp.NivelGravedad > 0){
            
            Ventana3 ventana = new Ventana3();
            ventana.setLocationRelativeTo(null);
            ventana.setVisible(true);
           this.setVisible(false);
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel etiCientificoIncorrecto;
    private javax.swing.JLabel etiNombreIncorrecto;
    private javax.swing.JLabel etigravedad0;
    private javax.swing.JSlider slGravedad;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtCientifico;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}

